### PR TITLE
AML-16 Allow GridSearch=None

### PR DESCRIPTION
**Pull request by tstreule**
Additionally, the testing code for grid search has been simplified.

### CODE REVIEW

**Comment by tstreule** [comment]
Please first accept #14 as I pulled these changes already in this branch.

**Comment by tstreule** [comment]
Additinally, please consider using this commit message for "Squash and merge":

```
AML-16 Allow GridSearch=None (#15)

* Simplify code for grid search testing

* Allow grid_search_type=None and grid_search_iterations=0 and add test case to check presence of hyperparameters
```

**Comment by nielsuit227** [comment]
Can do, but any idea why these tests are failing?

**Comment by tstreule** [comment]
Not sure but I assume the randomness of the dummy data could have an impact.

I propose to make a Jira issue for that.

**Pull request merged**
